version: '3'

services:
  gncs-restful-api:
    build:
      context: './'
      dockerfile: Dockerfile.development
    depends_on:
      - mongo
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DATABASE_NAME}
      - NODE_ENV=development
    volumes:
      - .:/usr/src/node-app
    networks:
      - gncs-network

  mongo:
    image: mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - ./mongodb:/data/db
    networks:
      - gncs-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      # - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongo
    ports:
      - '5001:8081'
    networks:
      - gncs-network
    restart: always

networks:
  gncs-network:
    driver: bridge
